blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('', views.blog, name='blog'),
    path('categoria/<int:id>/', views.categoria, name='categoria'),
    
]

carro/urls.py
from django.urls import path
from . import views

app_name ="carro"

urlpatterns = [
        path('agregar/<int:id>/', views.agregar, name='agregar'),
        path('eliminar/<int:id>/', views.eliminar, name='eliminar'),
        path('restar/<int:id>/', views.restar, name='restar'),   
        path('vaciar/', views.vaciar, name='vaciar'),
]

contacto/urls.py
from django.urls import path
from . import views


urlpatterns = [     
    path('', views.contacto, name='contacto'),   
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('servicios/', include('servicios.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
]

servicios/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('', views.servicios, name='servicios'),
    
]

tienda/urls.py
from django.urls import path
from . import views


urlpatterns = [
        path('', views.tienda, name='tienda'),   
]

webapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('servicios', views.servicios, name='servicios'),
    path('blog', views.blog, name='blog'),
    path('contacto', views.contacto, name='contacto'),
    path('tienda', views.tienda, name='tienda'),   
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Categoria(models.Model):
    nombre = models.CharField(max_length=50)    
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "categoria"
        verbose_name_plural = "categorias"

    def __str__(self):
        return self.nombre     

class Post(models.Model):
    titulo = models.CharField(max_length=50)
    contenido = models.TextField()
    imagen = models.ImageField(upload_to="blog", null=True, blank=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    categorias = models.ManyToManyField(Categoria)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "post"
        verbose_name_plural = "posts"

    def __str__(self):
        return self.titulo     
        

carro/models.py
from django.db import models

# Create your models here.

contacto/models.py
from django.db import models

class Contacto(models.Model):
    nombre = models.CharField(max_length=200, verbose_name="nombre", blank=True, null=True)
    email = models.EmailField(max_length=200, verbose_name="email", blank=True, null=True )
    telefono = models.CharField(max_length=15)
    mensaje = models.TextField()

    def __str__(self):
        return self.nombre

servicios/models.py
from django.db import models

# Create your models here.
class Servicio(models.Model):
    titulo = models.CharField(max_length=50)
    contenido = models.TextField()
    imagen = models.ImageField(upload_to="servicios")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "servicio"
        verbose_name_plural = "servicios"

    def __str__(self):
        return self.titulo     

tienda/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "categoria"
        verbose_name_plural = "categorias"

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre =models.CharField(max_length=200, blank=True, null=True)
    categoria = models.ForeignKey(Categoria, on_delete =models.CASCADE)
    imagen = models.ImageField(upload_to="tienda", null=True, blank=True )
    precio = models.FloatField()
    disponibilidad = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = "producto"
        verbose_name = "productos"           

    def __str__(self):
        return self.nombre    

contacto/forms.py
from django import forms
from .models import Contacto

class FormularioContacto(forms.ModelForm):

    nombre = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    email = forms.EmailField(widget=forms.TextInput(attrs={"class": "form-control"}))
    telefono = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    mensaje = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}))

    class Meta:
        model = Contacto
        fields = "__all__"
    

 

blog/views.py
from django.shortcuts import render
from .models import *

# Create your views here.
def blog(request):
    posts = Post.objects.all()
    
    contexto = {'posts': posts}
    
    return render(request, 'blog/blog.html', contexto)

def categoria(request, id):
    categoria = Categoria.objects.get(id=id)
    posts = Post.objects.filter(categorias = categoria)
    contexto = {'categoria': categoria, 'posts': posts}
    return render(request, 'blog/categorias.html', contexto )

carro/views.py
from django.shortcuts import render, redirect
from .carro import Carro 
from tienda.models import Producto

# Create your views here.


def agregar(request, id):
    carro = Carro(request)
    producto = Producto.objects.get(id=id)
    carro.agregar(producto=producto)
    return redirect("tienda")

def eliminar(request, id):
    carro = Carro(request)
    producto = Producto.objects.get(id=id)
    carro.eliminar(producto=producto)
    return redirect("tienda")    

def restar(request, id):
    carro = Carro(request)
    producto = Producto.objects.get(id=id)
    carro.restar(producto=producto)
    return redirect("tienda")    

def vaciar(request, id):
    carro = Carro(request)
    carro.vaciar()
 
    return redirect("tienda")    

contacto/views.py
from django.shortcuts import render, redirect
from .forms import FormularioContacto 
from django.core.mail import EmailMessage


# Create your views here.


def contacto(request):
    form = FormularioContacto()

    if request.method == "POST":
        form = FormularioContacto(data=request.POST)
        if form.is_valid:
            nombre = request.POST.get("nombre")
            email = request.POST.get("email")
            mensaje = request.POST.get("mensaje")

            email = EmailMessage('Mensaje desde la App Ecommerce', 
                    "El Usuario {}, del mail {} escribió : {}".format(nombre, email, mensaje),
                     "",
                     ["pruebasdev15@gmail.com"], 
                     )
           
            try:
                email.send()       
                return redirect("/contacto/?valido")
            except:
                return redirect("/contacto/?NoValido")

    contexto = {'form': form}
    
    return render(request, 'contacto/contacto.html', contexto)

    

servicios/views.py
from django.shortcuts import render
from .models import Servicio

def servicios(request):
    
    servicios = Servicio.objects.all()
    contexto = {'servicios': servicios}

    return render(request, 'servicios/servicios.html', contexto)

tienda/views.py
from django.shortcuts import render
from .models import Producto

# Create your views here.

def tienda(request):
    productos = Producto.objects.all()
    contexto = {'productos': productos}

    return render(request, 'tienda/tienda.html', contexto)

webapp/views.py
from django.shortcuts import render


# Create your views here.
def inicio(request):
    
    return render(request, 'webapp/inicio.html', {})

blog/templates/blog/blog.html
{% extends "base.html" %}  

{% load static %} 

{% block content %} 
<div class="container">

  {% for post in posts %} 
<div class="card m-3 border-2 border-info" style="width: 100%;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{post.imagen.url}}" class=" rounded mt-5 m-lg-3" alt="..." >
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{post.titulo}}</h5>
        <p class="card-text">{{post.contenido}}</p>
        <p class="card-text"><small class="text-muted">{{post.updated}}</small></p>
      </div>
      <div class="footer ">
        
        <a href = "#" class="row ">{{post.categoria}}</a>
       
      </div>
    </div>
  </div>
</div>
{% endfor %}
</div> 

{% endblock %}  

blog/templates/blog/categorias.html
{% extends "base.html" %}  

{% load static %} 

{% block content %} 

{% for post in posts %} 

<section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{{post.imagen.url}}" alt="" style="width: 50%;">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4" >
            <span class="section-heading-lower">{{post.titulo}}</span>           
          </h2>
          <h3>
            <span class="section-heading-upper">{{post.contenido}}</span>
          </h3>
          <div>
            <span class="section-heading-upper" style="font-size: 10px;">Autor : {{post.autor}}</span>
          </div>                     
        </div>
      </div>
    </div>
  </section>
{% endfor %}  

    <section>
        <div style="width:75%; color:white; margin:0 auto; text-align: center; padding: 15px;"> 
          
          Categorias: 

          {% for post in posts %} 

            {% for categoria in post.categorias.all %}
      
            <a href = "" class="linksCategorias"> {{categoria.nombre}} </a>&nbsp;

            {% endfor %}  

         {% endfor %}  
        
        </div>
      </section>
    

{% endblock %}  

contacto/templates/contacto/contacto.html
{% extends "base.html" %}  

{% load static %} 

{% block content %} 

  <div class="row mt-3" style="margin: 0px auto; display:flex; justify-content: space-evenly;">
  <div class="col-md-5 m-3  border border-2 border-info rounded text-primary">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d95762.98686796894!2d-75.73197437424759!3d41.4046370239794!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c4d93a77484bbb%3A0xfff27920ab9bfae8!2sScranton%2C%20Pensilvania%2C%20EE.%20UU.!5e0!3m2!1ses-419!2sar!4v1635963957361!5m2!1ses-419!2sar"  style="width: 95%; height: 95%; margin: 0px auto;" allowfullscreen="" loading="lazy" class="border border-2 border-warning rounded m-3"></iframe>
  </div>

  <div class="col-md-5 m-3  border border-2 border-info rounded text-primary">

      {% if "valido" in request.GET %}
        <p class="bg-success rounded mt-2 text-white text-center p-1">Información enviada con éxito!</p>
      {% endif %}  
      <form action="" method="POST" style="text-align: center;">
        {% csrf_token %}

        <table style=" margin: 20px auto;">
            {{form.as_table }}
        </table>
        <input type="submit" value="enviar" style="width: 150px;" class="btn btn-outline-success">

      </form>
    
  </div>
</div>

{% endblock %}

servicios/templates/servicios/servicios.html
{% extends "base.html" %}  

{% load static %} 

{% block content %} 

<div class="container  mt-4 border border-2 border-info rounded">
<div id="carouselExampleDark" class="carousel carousel-dark slide p-sm-4" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="10000">
      <img src="{% static './webapp/img/inicio2.jfif' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Primer Servicio</h5>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <img src="{% static './webapp/img/inicio1.jfif' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Segundo Servicio</h5>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static './webapp/img/inicio3.jfif' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Tercer Servicio</h5>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
      </div>
    </div>
    
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>
{% endblock %}

templates/webapp/inicio.html
{% extends "base.html" %}  

{% load static %} 

{% block content %} 

<h1>inicio</h1>

{% endblock %}

tienda/templates/carro/widget.html
<table class="table table-bordered border border-primary border-2">
    <thead>
        <tr>
            <th colspan="3" class="text-center ">
                Tu Carro
            </th>
        </tr>
        <tr>
            <th class="text-center ">Producto</th>
            <th class="text-center ">Cantidad</th>
            <th class="text-center ">Subtotal</th>
        </tr>
    </thead>
    <tbody >
        {% if request.session.carro.items %} 
            {% for key, value in request.session.carro.items %}  
            <tr class="text-center">
                <td>{{value.nombre}}</td>
                <td>{{value.cantidad}}</td>
                <td>
                 <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                 <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a><br/>
                 {{value.precio}}
                </td>
            </tr>
 
            {% endfor %}  

            {% else %}  
            <tr>
             <td colspan="3">
                 <div class="alert alert-danger text-center">Sin Productos</div>
             </td>
            </tr>
             {% endif %}     
     </tbody>
 <tfoot >
     <tr>
         <td colspan="3" >
             Total:  &nbsp;  &nbsp;  $ <!--{{importe_total}}-->
         </td>
     </tr>
 </tfoot>
 
  
</table>

tienda/templates/tienda/tienda.html
{% extends "base.html" %}  

{% load static %} 

{% block content %} 
<div class="container mt-5">
<div class="row row-cols-sm-5 row-cols-md-3 g-4">
  {% for producto in productos %} 
  <div class="col">

    <div class="card border-2 border-info">
      <img src="{{producto.imagen.url}}" class="card-img-top p-2 " alt="...">
      <div class="card-body">
        <h5 class="card-title">{{producto.nombre}}</h5>
        <h6 class="card-subtitle mb-2 text-muted">$  {{producto.precio}}</h6>       
        <a href="#" class="card-link"> + Info </a>
        <a href="#" class="card-link">+ {{producto.categoria}}</a>
      </div>
       <div class="footer p-2">
        <a href="#" class="btn btn-outline-success">Agregar al Carro</a>
        <a href="#" class="btn btn-success">Comprar</a>
      </div>
    </div>
   
  </div>
  {% endfor %}  
</div>
</div>

   

 <!--div class="col-2" style="float:right ; margin-top: 15px;">
   
           < {% include "carro/widget.html" %} >
        
        </div--></div>
{% endblock %}

webapp/templates/base.html
<html>

<head>
    {% load static %} 

  
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Styles -->
    
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom border-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"><img src="{% static './webapp/img/dmf.jpg' %}" style="margin: 10px;"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll " style="--bs-scroll-height: 100px; margin-left: auto;">
          <li class="nav-item  px-lg-4">
            <a class="nav-link text-uppercase text-expanded {% if request.path == '/' %}active{% endif %}" href="{% url 'inicio' %}">Empresa</a>
          </li>
          <li class="nav-item  px-lg-4">
            <a class="nav-link text-uppercase text-expanded {% if request.path == 'servicios/' %}active{% endif %}" href="{% url 'servicios' %}">Servicios</a>
          </li>
          <li class="nav-item  px-lg-4">
            <a class="nav-link text-uppercase text-expanded {% if request.path == 'tienda/' %}active{% endif %}" href="{% url 'tienda' %}">Productos</a>
          </li>
          <li class="nav-item  px-lg-4">
            <a class="nav-link text-uppercase text-expanded {% if request.path|slice:':5' == 'blog/' %}active{% endif %}" href="{% url 'blog' %}">Blog</a>
          </li>
          <li class="nav-item px-lg-4">
            <a class="nav-link text-uppercase text-expanded {% if request.path == 'contacto/' %}active{% endif %} " href="{% url 'contacto' %}">Contacto</a>
          </li>               
        </ul>
        <a class="navbar-brand" href="#">
         
          <img src="https://img.icons8.com/ios/50/000000/shopping-cart.png" alt="" width="50" class="d-inline-block align-text-top" style="margin-right: 35px; margin-left: 35px;">
          
        </a>
      </div>
    </div>
  </nav>
 
  {% block content %} 

  {% endblock %} 

    <!-- Footer -->
    <footer class=" border-top border-primary text-center mt-5">        
        <p class="p-2"> Hecho x mí :) - Octubre 2021</p>     
	  </footer>
  </div>
  </div>
  </div>
    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>


</html>

webapp/templates/webapp/inicio.html
{% extends "base.html" %}  

{% load static %} 

{% block content %} 

<div class="container border border-2 border-info rounded mt-3 ">
  <div class="row ">
    <div class="col-6 p-3 m-5">
      <h1>Nuestra Empresa</h1>
      <p style="text-align: justify;">The standard Lorem Ipsum passage, used since the 1500s
        "Lorem ipsum dolor sit amet, consectetur aididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
        </p >
       </div>
    <div  class="col-4 pl-5" style="display: flex; align-items: center;">
      <img src="{% static './webapp/img/principal.jpg' %}" style="width: 100%;">
    </div>
  </div>
</div>


{% endblock %}